// Code generated by go run generate-tests.go.

// Copyright 2017 Tom Thorogood. All rights reserved.
// Use of this source code is governed by a
// Modified BSD License that can be found in
// the LICENSE file.

package atomics

import (
	"testing"
	"testing/quick"
)

func TestInt32Default(t *testing.T) {
	var c Int32
	if c.Load() != 0 {
		t.Fatal("invalid default value")
	}
}

func TestNewInt32(t *testing.T) {
	if NewInt32(0) == nil {
		t.Fatal("NewInt32 returned nil")
	}
}

func TestInt32UnsafeRaw(t *testing.T) {
	var c Int32
	if c.UnsafeRaw() == nil {
		t.Fatal("UnsafeRaw returned nil")
	}
}

func TestInt32Load(t *testing.T) {
	if err := quick.Check(func(v int32) bool {
		return NewInt32(v).Load() == v
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestInt32Store(t *testing.T) {
	if err := quick.Check(func(v int32) bool {
		var c Int32
		c.Store(v)
		return c.Load() == v
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestInt32Swap(t *testing.T) {
	if err := quick.Check(func(old, new int32) bool {
		c := NewInt32(old)
		return c.Swap(new) == old && c.Load() == new
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestInt32CompareAndSwap(t *testing.T) {
	if err := quick.Check(func(old, new int32) bool {
		c := NewInt32(old)
		return !c.CompareAndSwap(-old, new) &&
			c.Load() == old &&
			c.CompareAndSwap(old, new) &&
			c.Load() == new
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestInt32Add(t *testing.T) {
	if err := quick.Check(func(v, delta int32) bool {
		c := NewInt32(v)
		v += delta
		return c.Add(delta) == v && c.Load() == v
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestInt32Increment(t *testing.T) {
	if err := quick.Check(func(v int32) bool {
		c := NewInt32(v)
		v++
		return c.Increment() == v && c.Load() == v
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestInt32Subtract(t *testing.T) {
	if err := quick.Check(func(v, delta int32) bool {
		c := NewInt32(v)
		v -= delta
		return c.Subtract(delta) == v && c.Load() == v
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestInt32Decrement(t *testing.T) {
	if err := quick.Check(func(v int32) bool {
		c := NewInt32(v)
		v--
		return c.Decrement() == v && c.Load() == v
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestInt32Reset(t *testing.T) {
	if err := quick.Check(func(v int32) bool {
		c := NewInt32(v)
		return c.Reset() == v && c.Load() == 0
	}, nil); err != nil {
		t.Fatal(err)
	}
}
