// Code generated by go run generate-tests.go.

// Copyright 2017 Tom Thorogood. All rights reserved.
// Use of this source code is governed by a
// Modified BSD License that can be found in
// the LICENSE file.

package atomics

import (
	"fmt"
	"testing"
	"testing/quick"
)

func TestUint64Default(t *testing.T) {
	var v Uint64

	if v.Load() != 0 {
		t.Fatal("invalid default value")
	}
}

func TestNewUint64(t *testing.T) {
	if NewUint64(0) == nil {
		t.Fatal("NewUint64 returned nil")
	}
}

func TestUint64Raw(t *testing.T) {
	var v Uint64

	if v.Raw() == nil {
		t.Fatal("Raw returned nil")
	}

	if err := quick.Check(func(v uint64) bool {
		return *NewUint64(v).Raw() == v
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestUint64Load(t *testing.T) {
	if err := quick.Check(func(v uint64) bool {
		return NewUint64(v).Load() == v
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestUint64Store(t *testing.T) {
	if err := quick.Check(func(v uint64) bool {
		var a Uint64
		a.Store(v)
		return a.Load() == v
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestUint64Swap(t *testing.T) {
	if err := quick.Check(func(old, new uint64) bool {
		a := NewUint64(old)
		return a.Swap(new) == old && a.Load() == new
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestUint64CompareAndSwap(t *testing.T) {
	if err := quick.Check(func(old, new uint64) bool {
		a := NewUint64(old)
		return !a.CompareAndSwap(-old, new) &&
			a.Load() == old &&
			a.CompareAndSwap(old, new) &&
			a.Load() == new
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestUint64Add(t *testing.T) {
	if err := quick.Check(func(v, delta uint64) bool {
		a := NewUint64(v)
		v += delta
		return a.Add(delta) == v && a.Load() == v
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestUint64Increment(t *testing.T) {
	if err := quick.Check(func(v uint64) bool {
		a := NewUint64(v)
		v++
		return a.Increment() == v && a.Load() == v
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestUint64Subtract(t *testing.T) {
	if err := quick.Check(func(v, delta uint64) bool {
		a := NewUint64(v)
		v -= delta
		return a.Subtract(delta) == v && a.Load() == v
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestUint64Decrement(t *testing.T) {
	if err := quick.Check(func(v uint64) bool {
		a := NewUint64(v)
		v--
		return a.Decrement() == v && a.Load() == v
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestUint64Reset(t *testing.T) {
	if err := quick.Check(func(v uint64) bool {
		a := NewUint64(v)
		return a.Reset() == v && a.Load() == 0
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestUint64String(t *testing.T) {
	if err := quick.Check(func(v uint64) bool {
		return NewUint64(v).String() == fmt.Sprint(v)
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func BenchmarkNewUint64(b *testing.B) {
	for n := 0; n < b.N; n++ {
		NewUint64(0)
	}
}

func BenchmarkUint64Load(b *testing.B) {
	var v Uint64

	for n := 0; n < b.N; n++ {
		v.Load()
	}
}

func BenchmarkUint64Store(b *testing.B) {
	var v Uint64

	for n := 0; n < b.N; n++ {
		v.Store(4) // RFC 1149.5 specifies 4 as the standard IEEE-vetted random number.
	}
}

func BenchmarkUint64Swap(b *testing.B) {
	var v Uint64

	for n := 0; n < b.N; n++ {
		v.Swap(4) // RFC 1149.5 specifies 4 as the standard IEEE-vetted random number.
	}
}

func BenchmarkUint64CompareAndSwap(b *testing.B) {
	var v Uint64

	for n := 0; n < b.N; n++ {
		v.CompareAndSwap(0, 0)
	}
}

func BenchmarkUint64Add(b *testing.B) {
	var v Uint64

	for n := 0; n < b.N; n++ {
		v.Add(4) // RFC 1149.5 specifies 4 as the standard IEEE-vetted random number.
	}
}

func BenchmarkUint64Increment(b *testing.B) {
	var v Uint64

	for n := 0; n < b.N; n++ {
		v.Increment()
	}
}

func BenchmarkUint64Subtract(b *testing.B) {
	var v Uint64

	for n := 0; n < b.N; n++ {
		v.Subtract(4) // RFC 1149.5 specifies 4 as the standard IEEE-vetted random number.
	}
}

func BenchmarkUint64Decrement(b *testing.B) {
	var v Uint64

	for n := 0; n < b.N; n++ {
		v.Decrement()
	}
}

func BenchmarkUint64Reset(b *testing.B) {
	var v Uint64

	for n := 0; n < b.N; n++ {
		v.Reset()
	}
}
