// Code generated by go run generate-tests.go.

// Copyright 2017 Tom Thorogood. All rights reserved.
// Use of this source code is governed by a
// Modified BSD License that can be found in
// the LICENSE file.

package atomics

import (
	"testing"
	"testing/quick"
)

func TestNewUint64(t *testing.T) {
	if NewUint64(0) == nil {
		t.Fatal("NewUint64 returned nil")
	}
}

func TestUint64UnsafeRaw(t *testing.T) {
	var c Uint64
	if c.UnsafeRaw() == nil {
		t.Fatal("UnsafeRaw returned nil")
	}
}

func TestUint64Load(t *testing.T) {
	if err := quick.Check(func(v uint64) bool {
		return NewUint64(v).Load() == v
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestUint64Store(t *testing.T) {
	if err := quick.Check(func(v uint64) bool {
		var c Uint64
		c.Store(v)
		return c.Load() == v
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestUint64Swap(t *testing.T) {
	if err := quick.Check(func(old, new uint64) bool {
		c := NewUint64(old)
		return c.Swap(new) == old && c.Load() == new
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestUint64CompareAndSwap(t *testing.T) {
	if err := quick.Check(func(old, new uint64) bool {
		c := NewUint64(old)
		return !c.CompareAndSwap(-old, new) &&
			c.Load() == old &&
			c.CompareAndSwap(old, new) &&
			c.Load() == new
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestUint64Add(t *testing.T) {
	if err := quick.Check(func(v, delta uint64) bool {
		c := NewUint64(v)
		v += delta
		return c.Add(delta) == v && c.Load() == v
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestUint64Increment(t *testing.T) {
	if err := quick.Check(func(v uint64) bool {
		c := NewUint64(v)
		v++
		return c.Increment() == v && c.Load() == v
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestUint64Subtract(t *testing.T) {
	if err := quick.Check(func(v, delta uint64) bool {
		c := NewUint64(v)
		v -= delta
		return c.Subtract(delta) == v && c.Load() == v
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestUint64Decrement(t *testing.T) {
	if err := quick.Check(func(v uint64) bool {
		c := NewUint64(v)
		v--
		return c.Decrement() == v && c.Load() == v
	}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestUint64Reset(t *testing.T) {
	if err := quick.Check(func(v uint64) bool {
		c := NewUint64(v)
		return c.Reset() == v && c.Load() == 0
	}, nil); err != nil {
		t.Fatal(err)
	}
}
