// Code generated by go run generate-int.go.

// Copyright 2017 Tom Thorogood. All rights reserved.
// Use of this source code is governed by a
// Modified BSD License that can be found in
// the LICENSE file.

package maps

import (
	"sync"

	"github.com/tmthrgd/atomics"
)

// Bool provides a map of atomic bools.
type Bool struct {
	m sync.Map // map[interface{}]*atomics.Bool
}

// Retrieve returns the atomics.Bool associated with
// the given key or nil if it does not exist in the map.
func (m *Bool) Retrieve(key interface{}) *atomics.Bool {
	v, ok := m.m.Load(key)
	if !ok {
		return nil
	}

	return v.(*atomics.Bool)
}

// Insert inserts the atomics.Bool into the map for
// the given key.
func (m *Bool) Insert(key interface{}, val *atomics.Bool) {
	m.m.Store(key, val)
}

// Value returns the atomics.Bool associated with the
// given key or atomically inserts a new atomics.Bool
// into the map if an entry did not exist in the map
// for the given key.
func (m *Bool) Value(key interface{}) *atomics.Bool {
	v, ok := m.m.Load(key)
	if !ok {
		v, _ = m.m.LoadOrStore(key, new(atomics.Bool))
	}

	return v.(*atomics.Bool)
}

// Delete removes an atomics.Bool from the map.
func (m *Bool) Delete(key interface{}) {
	m.m.Delete(key)
}

// Range calls f for each entry in the map. If f
// returns false Range stops iterating over the map.
func (m *Bool) Range(f func(key interface{}, val *atomics.Bool) bool) {
	m.m.Range(func(key, val interface{}) bool {
		return f(key, val.(*atomics.Bool))
	})
}

// Load is a wrapper for Value(key).Load().
func (m *Bool) Load(key interface{}) (val bool) {
	return m.Value(key).Load()
}

// Store is a wrapper for Value(key).Store(val).
func (m *Bool) Store(key interface{}, val bool) {
	m.Value(key).Store(val)
}

// Swap is a wrapper for Value(key).Swap(new).
func (m *Bool) Swap(key interface{}, new bool) (old bool) {
	return m.Value(key).Swap(new)
}

// CompareAndSwap is a wrapper for
// Value(key).CompareAndSwap(old, new).
func (m *Bool) CompareAndSwap(key interface{}, old, new bool) (swapped bool) {
	return m.Value(key).CompareAndSwap(old, new)
}

// Set is a wrapper for Value(key).Set().
func (m *Bool) Set(key interface{}) (old bool) {
	return m.Value(key).Set()
}

// Reset is a wrapper for Value(key).Reset().
func (m *Bool) Reset(key interface{}) (old bool) {
	return m.Value(key).Reset()
}
