// Code generated by go run generate-int.go.

// Copyright 2017 Tom Thorogood. All rights reserved.
// Use of this source code is governed by a
// Modified BSD License that can be found in
// the LICENSE file.

package maps

import (
	"sync"

	"github.com/tmthrgd/atomics"
)

// Float64 provides a map of atomic float64s.
type Float64 struct {
	m sync.Map // map[interface{}]*atomics.Float64
}

// Retrieve returns the atomics.Float64 associated with
// the given key or nil if it does not exist in the map.
func (m *Float64) Retrieve(key interface{}) *atomics.Float64 {
	v, ok := m.m.Load(key)
	if !ok {
		return nil
	}

	return v.(*atomics.Float64)
}

// Insert inserts the atomics.Float64 into the map for
// the given key.
func (m *Float64) Insert(key interface{}, val *atomics.Float64) {
	m.m.Store(key, val)
}

// Value returns the atomics.Float64 associated with the
// given key or atomically inserts a new atomics.Float64
// into the map if an entry did not exist in the map
// for the given key.
func (m *Float64) Value(key interface{}) *atomics.Float64 {
	v, ok := m.m.Load(key)
	if !ok {
		v, _ = m.m.LoadOrStore(key, new(atomics.Float64))
	}

	return v.(*atomics.Float64)
}

// Delete removes an atomics.Float64 from the map.
func (m *Float64) Delete(key interface{}) {
	m.m.Delete(key)
}

// Range calls f for each entry in the map. If f
// returns false Range stops iterating over the map.
func (m *Float64) Range(f func(key interface{}, val *atomics.Float64) bool) {
	m.m.Range(func(key, val interface{}) bool {
		return f(key, val.(*atomics.Float64))
	})
}

// Load is a wrapper for Value(key).Load().
func (m *Float64) Load(key interface{}) (val float64) {
	return m.Value(key).Load()
}

// Store is a wrapper for Value(key).Store(val).
func (m *Float64) Store(key interface{}, val float64) {
	m.Value(key).Store(val)
}

// Swap is a wrapper for Value(key).Swap(new).
func (m *Float64) Swap(key interface{}, new float64) (old float64) {
	return m.Value(key).Swap(new)
}

// CompareAndSwap is a wrapper for
// Value(key).CompareAndSwap(old, new).
func (m *Float64) CompareAndSwap(key interface{}, old, new float64) (swapped bool) {
	return m.Value(key).CompareAndSwap(old, new)
}

// Add is a wrapper for Value(key).Add(delta).
func (m *Float64) Add(key interface{}, delta float64) (new float64) {
	return m.Value(key).Add(delta)
}

// Increment is a wrapper for Value(key).Increment().
func (m *Float64) Increment(key interface{}) (new float64) {
	return m.Value(key).Increment()
}

// Subtract is a wrapper for Value(key).Subtract(delta).
func (m *Float64) Subtract(key interface{}, delta float64) (new float64) {
	return m.Value(key).Subtract(delta)
}

// Decrement is a wrapper for Value(key).Decrement().
func (m *Float64) Decrement(key interface{}) (new float64) {
	return m.Value(key).Decrement()
}

// Reset is a wrapper for Value(key).Reset().
func (m *Float64) Reset(key interface{}) (old float64) {
	return m.Value(key).Reset()
}
