// Code generated by go run generate-int.go.

// Copyright 2017 Tom Thorogood. All rights reserved.
// Use of this source code is governed by a
// Modified BSD License that can be found in
// the LICENSE file.

package maps

import (
	"sync"

	"github.com/tmthrgd/atomics"
)

// Int64 provides a map of atomic int64s.
type Int64 struct {
	m sync.Map // map[interface{}]*atomics.Int64
}

// Retrieve returns the atomics.Int64 associated with
// the given key or nil if it does not exist in the map.
func (m *Int64) Retrieve(key interface{}) *atomics.Int64 {
	v, ok := m.m.Load(key)
	if !ok {
		return nil
	}

	return v.(*atomics.Int64)
}

// Insert inserts the atomics.Int64 into the map for
// the given key.
func (m *Int64) Insert(key interface{}, val *atomics.Int64) {
	m.m.Store(key, val)
}

// Value returns the atomics.Int64 associated with the
// given key or atomically inserts a new atomics.Int64
// into the map if an entry did not exist in the map
// for the given key.
func (m *Int64) Value(key interface{}) *atomics.Int64 {
	v, ok := m.m.Load(key)
	if !ok {
		v, _ = m.m.LoadOrStore(key, new(atomics.Int64))
	}

	return v.(*atomics.Int64)
}

// Delete removes an atomics.Int64 from the map.
func (m *Int64) Delete(key interface{}) {
	m.m.Delete(key)
}

// Range calls f for each entry in the map. If f
// returns false Range stops iterating over the map.
func (m *Int64) Range(f func(key interface{}, val *atomics.Int64) bool) {
	m.m.Range(func(key, val interface{}) bool {
		return f(key, val.(*atomics.Int64))
	})
}

// Load is a wrapper for Value(key).Load().
func (m *Int64) Load(key interface{}) (val int64) {
	return m.Value(key).Load()
}

// Store is a wrapper for Value(key).Store(val).
func (m *Int64) Store(key interface{}, val int64) {
	m.Value(key).Store(val)
}

// Swap is a wrapper for Value(key).Swap(new).
func (m *Int64) Swap(key interface{}, new int64) (old int64) {
	return m.Value(key).Swap(new)
}

// CompareAndSwap is a wrapper for
// Value(key).CompareAndSwap(old, new).
func (m *Int64) CompareAndSwap(key interface{}, old, new int64) (swapped bool) {
	return m.Value(key).CompareAndSwap(old, new)
}

// Add is a wrapper for Value(key).Add(delta).
func (m *Int64) Add(key interface{}, delta int64) (new int64) {
	return m.Value(key).Add(delta)
}

// Increment is a wrapper for Value(key).Increment().
func (m *Int64) Increment(key interface{}) (new int64) {
	return m.Value(key).Increment()
}

// Subtract is a wrapper for Value(key).Subtract(delta).
func (m *Int64) Subtract(key interface{}, delta int64) (new int64) {
	return m.Value(key).Subtract(delta)
}

// Decrement is a wrapper for Value(key).Decrement().
func (m *Int64) Decrement(key interface{}) (new int64) {
	return m.Value(key).Decrement()
}

// Reset is a wrapper for Value(key).Reset().
func (m *Int64) Reset(key interface{}) (old int64) {
	return m.Value(key).Reset()
}
