// Code generated by go run generate-int.go.

// Copyright 2017 Tom Thorogood. All rights reserved.
// Use of this source code is governed by a
// Modified BSD License that can be found in
// the LICENSE file.

package maps

import (
	"sync"

	"github.com/tmthrgd/atomics"
)

// String provides a map of atomic strings.
type String struct {
	m sync.Map // map[interface{}]*atomics.String
}

// Retrieve returns the atomics.String associated with
// the given key or nil if it does not exist in the map.
func (m *String) Retrieve(key interface{}) *atomics.String {
	v, ok := m.m.Load(key)
	if !ok {
		return nil
	}

	return v.(*atomics.String)
}

// Insert inserts the atomics.String into the map for
// the given key.
func (m *String) Insert(key interface{}, val *atomics.String) {
	m.m.Store(key, val)
}

// Value returns the atomics.String associated with the
// given key or atomically inserts a new atomics.String
// into the map if an entry did not exist in the map
// for the given key.
func (m *String) Value(key interface{}) *atomics.String {
	v, ok := m.m.Load(key)
	if !ok {
		v, _ = m.m.LoadOrStore(key, new(atomics.String))
	}

	return v.(*atomics.String)
}

// Delete removes an atomics.String from the map.
func (m *String) Delete(key interface{}) {
	m.m.Delete(key)
}

// Range calls f for each entry in the map. If f
// returns false Range stops iterating over the map.
func (m *String) Range(f func(key interface{}, val *atomics.String) bool) {
	m.m.Range(func(key, val interface{}) bool {
		return f(key, val.(*atomics.String))
	})
}

// Load is a wrapper for Value(key).Load().
func (m *String) Load(key interface{}) (val string) {
	return m.Value(key).Load()
}

// Store is a wrapper for Value(key).Store(val).
func (m *String) Store(key interface{}, val string) {
	m.Value(key).Store(val)
}

// Swap is a wrapper for Value(key).Swap(new).
func (m *String) Swap(key interface{}, new string) (old string) {
	return m.Value(key).Swap(new)
}

// Reset is a wrapper for Value(key).Reset().
func (m *String) Reset(key interface{}) (old string) {
	return m.Value(key).Reset()
}
