// Code generated by go run generate-int.go.

// Copyright 2017 Tom Thorogood. All rights reserved.
// Use of this source code is governed by a
// Modified BSD License that can be found in
// the LICENSE file.

package maps

import (
	"sync"

	"github.com/tmthrgd/atomics"
)

// Uint32 provides a map of atomic uint32s.
type Uint32 struct {
	m sync.Map // map[interface{}]*atomics.Uint32
}

// Retrieve returns the atomics.Uint32 associated with
// the given key or nil if it does not exist in the map.
func (m *Uint32) Retrieve(key interface{}) *atomics.Uint32 {
	v, ok := m.m.Load(key)
	if !ok {
		return nil
	}

	return v.(*atomics.Uint32)
}

// Insert inserts the atomics.Uint32 into the map for
// the given key.
func (m *Uint32) Insert(key interface{}, val *atomics.Uint32) {
	m.m.Store(key, val)
}

// Value returns the atomics.Uint32 associated with the
// given key or atomically inserts a new atomics.Uint32
// into the map if an entry did not exist in the map
// for the given key.
func (m *Uint32) Value(key interface{}) *atomics.Uint32 {
	v, ok := m.m.Load(key)
	if !ok {
		v, _ = m.m.LoadOrStore(key, new(atomics.Uint32))
	}

	return v.(*atomics.Uint32)
}

// Delete removes an atomics.Uint32 from the map.
func (m *Uint32) Delete(key interface{}) {
	m.m.Delete(key)
}

// Range calls f for each entry in the map. If f
// returns false Range stops iterating over the map.
func (m *Uint32) Range(f func(key interface{}, val *atomics.Uint32) bool) {
	m.m.Range(func(key, val interface{}) bool {
		return f(key, val.(*atomics.Uint32))
	})
}

// Load is a wrapper for Value(key).Load().
func (m *Uint32) Load(key interface{}) (val uint32) {
	return m.Value(key).Load()
}

// Store is a wrapper for Value(key).Store(val).
func (m *Uint32) Store(key interface{}, val uint32) {
	m.Value(key).Store(val)
}

// Swap is a wrapper for Value(key).Swap(new).
func (m *Uint32) Swap(key interface{}, new uint32) (old uint32) {
	return m.Value(key).Swap(new)
}

// CompareAndSwap is a wrapper for
// Value(key).CompareAndSwap(old, new).
func (m *Uint32) CompareAndSwap(key interface{}, old, new uint32) (swapped bool) {
	return m.Value(key).CompareAndSwap(old, new)
}

// Add is a wrapper for Value(key).Add(delta).
func (m *Uint32) Add(key interface{}, delta uint32) (new uint32) {
	return m.Value(key).Add(delta)
}

// Increment is a wrapper for Value(key).Increment().
func (m *Uint32) Increment(key interface{}) (new uint32) {
	return m.Value(key).Increment()
}

// Subtract is a wrapper for Value(key).Subtract(delta).
func (m *Uint32) Subtract(key interface{}, delta uint32) (new uint32) {
	return m.Value(key).Subtract(delta)
}

// Decrement is a wrapper for Value(key).Decrement().
func (m *Uint32) Decrement(key interface{}) (new uint32) {
	return m.Value(key).Decrement()
}

// Reset is a wrapper for Value(key).Reset().
func (m *Uint32) Reset(key interface{}) (old uint32) {
	return m.Value(key).Reset()
}
